source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Pretracking_Example', :exclusive => true do
  pod 'Pretracking', :path => '../'
end

target 'Pretracking_Tests', :exclusive => true do
  pod 'Pretracking', :path => '../'


end
